apiVersion: chaos.harness.io/v1
description: added description
identity: gitx-backed-container-probe-mcm
infrastructureType: Kubernetes
inputs: null
kind: ProbeTemplate
name: gitx-backed-container-probe-mcm
probeProperties:
  containerProbe:
    affinity: {}
    args: echo "GitX Backed Hello World"
    command:
    - /bin/sh
    - -c
    comparator:
      criteria: matches
      type: string
      value: Hello World
    env: []
    hostIPC: false
    hostNetwork: false
    hostPID: false
    image: bitnami/kubectl:latest
    imagePullPolicy: IfNotPresent
    namespace: hce
    serviceAccountName: default
runProperties:
  attempt: 5
  initialDelay: 10s
  interval: 2s
  pollingInterval: 20s
  stopOnFailure: true
  timeout: 10s
  verbosity: info
tags:
- gitx:enabled
type: containerProbe
variables: []
