apiVersion: chaos.harness.io/v1
description: ""
identity: gitx-backed-probe-2-templ
infrastructureType: Kubernetes
inputs: null
kind: ProbeTemplate
name: gitx-backed-probe-2-templ-updated
probeProperties:
  httpProbe:
    method:
      get:
        criteria: contains
        responseBody: 200 OK
    tlsConfig:
      caFile: ""
      certFile: ""
      insecureSkipVerify: true
      keyFile: ""
    url: https://www.google.com
runProperties:
  attempt: 3
  initialDelay: 5s
  interval: 2s
  pollingInterval: 30s
  timeout: 30s
  verbosity: info
tags: []
type: httpProbe
variables: []
